### ISSUE TITLE
Stacking LSTMs

### ISSUE THREAD

**Issue by cyberbeat** [linkedin/dagli#13]
This is the code for LSTM stacking:

```
 public NNLSTMLayer stack(int... unitCounts) {
    Arguments.check(unitCounts.length > 0, "At least one unit count for at least one new layer must be provided");
    NNLSTMLayer previous = this.withUnitCount(unitCounts[0]).withInput(this.getInputLayer());

    for (int i = 1; i < unitCounts.length; i++) {
      previous = previous.withInput(previous).withUnitCount(unitCounts[i]);
    }

    return previous;
  }
```

I wonder, why the first stacked layer does not get `this` as input, but `this.getInputLayer()`?

**Comment by jeffpasternack** [comment]
The idea is that `stack(...)` returns a stack/sequence of layers "like" `this`, but the returned stack (as you point out) doesn't actually include `this`.  The nice thing about this is that you can thus conveniently define the sizes of all the layers with a single passed array (otherwise you'd have to define the size of the first layer separately), although I agree the semantics aren't obvious from the function name alone (perhaps something like `createStack(...)` would be more clear?)

**Comment by cyberbeat** [comment]
Oh, thanks, it would be good to clarify this in the javadoc, the name is ok.
